## Guacamole 20191108
# @tankmek
 
services:
# Configure MariaDB with persistent storage
# Need to init the db
  database:
    image: mariadb:10.11.2
    hostname: db_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql-root-pass'
      MYSQL_DATABASE: 'guacamole'
      MYSQL_USER: 'guacamole'
      MYSQL_PASSWORD: 'guacamole-user-pass'
    container_name: db_mysql 
    volumes:
      - "./db:/var/lib/mysql"
    secrets:
      - mysql-root
      - guacamole-user
 
# Configure proxy daemon
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: always
 
# Configure and link Guacamole to db and proxy
  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: always
    depends_on:
      - database
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db_mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

# Web Proxy
  gproxy:
    image: nginx:1.23.3
    hostname: gproxy
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./sites:/etc/nginx/sites-enabled/"
      - "./ssl:/etc/nginx/ssl"
    container_name: gproxy
    ports:
      - "443:443"
    depends_on:
      - guacamole
